[tool.briefcase]
project_name = "TGI"
bundle = "r2dr.tgi"
version = "0.0.1"
url = "https://tgi.r2dr/tgi"
license = "Proprietary"
author = 'cr2d20'
author_email = "cr2d20@tgi.r2dr"

[tool.briefcase.app.tgi]
formal_name = "TGI"
description = "POC for TGI "
icon = "src/tgi/resources/tgi"
sources = ['src/tgi']
requires = []


[tool.briefcase.app.tgi.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.tgi.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.tgi.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.tgi.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.tgi.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
